// Shared constants for the inventory domain (ADR-0035 slice 3).

// ---------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------

export const INVENTORY_SITE_NOT_FOUND = "INVENTORY_SITE_NOT_FOUND";
export const INVENTORY_PRODUCT_NOT_FOUND = "INVENTORY_PRODUCT_NOT_FOUND";
export const INVENTORY_LOT_EXPIRED_AT_RECEIPT = "INVENTORY_LOT_EXPIRED_AT_RECEIPT";
export const INVENTORY_EXPIRATION_MISMATCH = "INVENTORY_EXPIRATION_MISMATCH";
export const INVENTORY_TS_NOT_RECEIVED = "INVENTORY_TS_NOT_RECEIVED";
export const INVENTORY_RECEIPT_CONFLICT = "INVENTORY_RECEIPT_CONFLICT";
export const INVENTORY_LOT_NOT_FOUND = "INVENTORY_LOT_NOT_FOUND";
export const CATALOG_DUPLICATE_COMPOUND_PRODUCT = "CATALOG_DUPLICATE_COMPOUND_PRODUCT";
export const CATALOG_PRODUCT_CREATE_CONFLICT = "CATALOG_PRODUCT_CREATE_CONFLICT";
