// Render a `COMPLIANCE_NOTICE_V1` notification context into the
// subject + plain-text + HTML payload the email channel needs.
//
// Renderer kept SEPARATE from the channel adapter for the same
// reasons as `render-security-digest-email.ts`: focused unit tests,
// clean template-version bumps, and reusability by future non-email
// adapters (a Slack adapter renders the SAME context into a block).
//
// PHI invariant: the `ComplianceNotifier` port contract forbids PHI
// in the notice body, and the channel's `assertNoPhiInContext` gate
// has already run structurally. The renderer HTML-escapes everything
// anyway — the body lives inside a `<pre>` tag and a stray `<` in a
// future notice kind must not break the markup.

/**
 * Stable subject prefix so inbox filters and ticketing ingestion
 * rules key off the bracket prefix. Sibling of `[Pharmax security]`
 * on the nightly digest.
 */
const SUBJECT_PREFIX = "[Pharmax compliance]";

export type ComplianceNoticeSeverity = "info" | "warning" | "critical";

export interface ComplianceNoticeRenderInput {
  /** Machine-readable notice kind, e.g. "access-review.ready". */
  readonly noticeKind: string;
  /** The tenant org the notice concerns. */
  readonly organizationId: string;
  /** Human-readable subject; the renderer adds prefix + badge. */
  readonly subject: string;
  /** Pre-composed plain-text body, embedded verbatim. */
  readonly body: string;
  readonly severity: ComplianceNoticeSeverity;
  /** Optional evidence-artifact URI, rendered as a clickable link. */
  readonly evidenceUri?: string;
}

export interface RenderedComplianceNoticeEmail {
  readonly subject: string;
  readonly text: string;
  readonly html: string;
}

export function renderComplianceNoticeEmail(
  input: ComplianceNoticeRenderInput
): RenderedComplianceNoticeEmail {
  const badge = input.severity.toUpperCase();
  const subject = `${SUBJECT_PREFIX} ${badge} · ${input.subject}`;

  const textLines = [input.body.endsWith("\n") ? input.body.slice(0, -1) : input.body];
  textLines.push("");
  textLines.push(`Notice kind: ${input.noticeKind}`);
  textLines.push(`Organization: ${input.organizationId}`);
  if (input.evidenceUri !== undefined) {
    textLines.push(`Evidence: ${input.evidenceUri}`);
  }
  const text = `${textLines.join("\n")}\n`;

  return Object.freeze({ subject, text, html: renderHtml(input, badge) });
}

function renderHtml(input: ComplianceNoticeRenderInput, badge: string): string {
  const badgeColor =
    input.severity === "critical"
      ? { bg: "#fef2f2", fg: "#991b1b", border: "#fecaca" }
      : input.severity === "warning"
        ? { bg: "#fffbeb", fg: "#92400e", border: "#fde68a" }
        : { bg: "#eff6ff", fg: "#1e40af", border: "#bfdbfe" };

  const evidenceHtml =
    input.evidenceUri !== undefined
      ? `<p style="margin:16px 0 0;font-size:14px">Evidence: <a href="${escapeHtml(input.evidenceUri)}" style="color:#1d4ed8">${escapeHtml(input.evidenceUri)}</a></p>`
      : "";

  return `<!DOCTYPE html>
<html><body style="font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;background:#fafafa;padding:24px;color:#0a0a0a">
  <div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e5e5;border-radius:8px;padding:24px">
    <div style="display:inline-block;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:600;background:${badgeColor.bg};color:${badgeColor.fg};border:1px solid ${badgeColor.border}">${escapeHtml(badge)}</div>
    <h1 style="margin:12px 0 4px;font-size:20px">${escapeHtml(input.subject)}</h1>
    <p style="margin:0;color:#525252;font-size:14px">Notice <code style="font-size:12px">${escapeHtml(input.noticeKind)}</code> · Organization <code style="font-size:12px">${escapeHtml(input.organizationId)}</code></p>
    <hr style="border:none;border-top:1px solid #e5e5e5;margin:16px 0" />
    <pre style="margin:0;padding:12px;background:#fafafa;border:1px solid #e5e5e5;border-radius:6px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-word">${escapeHtml(input.body)}</pre>
    ${evidenceHtml}
    <p style="margin:24px 0 0;color:#737373;font-size:12px">SOC 2 evidence — generated by apps/worker compliance jobs. This message is operator-facing and does not contain PHI.</p>
  </div>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
