// scripts/operations/restore-drill-evidence.ts
//
// Pure composers for restore-drill evidence artifacts.
//
//   - `composeProvisionScript(args)` — emits the exact `aws rds`
//     bash from `docs/operations/restore-drill.md` §1 with the
//     operator's parameters substituted, so the operator copy-pastes
//     a generated script rather than hand-substituting variables in
//     the runbook (which is the error mode that gets you a typo'd
//     security group on a drill day).
//
//   - `composeTeardownScript(args)` — same for §4 destroy.
//
//   - `composeEvidenceMarkdown(record)` — emits the §3 evidence
//     template populated with the actual drill outcome, including
//     pass/fail per check + the captain's sign-off note.
//
//   - `composeEvidenceJson(record)` — machine-readable mirror; the
//     SOC 2 evidence-pack uploader can pick up the JSON without
//     parsing markdown.
//
// All composers are pure (no IO, no AWS, no DB). The CLI shell
// orchestrates IO + adapter calls and feeds the composer a frozen
// record at the end of each phase. Keeps this surface trivially
// testable and means a future "regenerate evidence from a JSON
// transcript" tool can reuse the same composer.

export interface ProvisionScriptArgs {
  readonly sourceClusterId: string;
  readonly drillClusterId: string;
  readonly drillInstanceId: string;
  readonly restoreTimeIso: string;
  readonly subnetGroup: string;
  readonly drillSecurityGroupId: string;
  /** `db.t4g.medium` per runbook §1.1b; override for serverless v2 sources. */
  readonly instanceClass: string;
}

export function composeProvisionScript(args: ProvisionScriptArgs): string {
  // Mirrors `docs/operations/restore-drill.md` §1 verbatim, modulo
  // variable substitution. Any drift between the two MUST also drift
  // in the runbook; the docs link to this composer for that reason.
  return [
    "#!/usr/bin/env bash",
    "# Generated by scripts/operations/run-restore-drill.ts --phase=provision-commands.",
    "# Source of truth for the steps is docs/operations/restore-drill.md §1.",
    "# Run this against the production AWS account. The operator (drill captain)",
    "# is responsible for the actual AWS calls — this script does NOT execute them.",
    "set -euo pipefail",
    "",
    "# ---- Variables (already substituted by the generator) ----------------------",
    `SRC_CLUSTER_ID=${shellQuote(args.sourceClusterId)}`,
    `RESTORE_TIME=${shellQuote(args.restoreTimeIso)}`,
    `NEW_CLUSTER_ID=${shellQuote(args.drillClusterId)}`,
    `NEW_INSTANCE_ID=${shellQuote(args.drillInstanceId)}`,
    `SUBNET_GROUP=${shellQuote(args.subnetGroup)}`,
    `DRILL_SG=${shellQuote(args.drillSecurityGroupId)}`,
    `INSTANCE_CLASS=${shellQuote(args.instanceClass)}`,
    "",
    "# ---- Step 1a: restore the cluster (storage) -------------------------------",
    "aws rds restore-db-cluster-to-point-in-time \\",
    '  --source-db-cluster-identifier "$SRC_CLUSTER_ID" \\',
    '  --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    '  --restore-to-time "$RESTORE_TIME" \\',
    '  --db-subnet-group-name "$SUBNET_GROUP" \\',
    '  --vpc-security-group-ids "$DRILL_SG" \\',
    "  --enable-cloudwatch-logs-exports postgresql \\",
    "  --deletion-protection",
    "",
    'aws rds wait db-cluster-available --db-cluster-identifier "$NEW_CLUSTER_ID"',
    "",
    "# ---- Step 1b: attach a single instance ------------------------------------",
    "aws rds create-db-instance \\",
    '  --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    '  --db-instance-identifier "$NEW_INSTANCE_ID" \\',
    "  --engine aurora-postgresql \\",
    '  --db-instance-class "$INSTANCE_CLASS" \\',
    "  --no-publicly-accessible",
    "",
    'aws rds wait db-instance-available --db-instance-identifier "$NEW_INSTANCE_ID"',
    "",
    "# ---- Resolve credentials + writer endpoint --------------------------------",
    'WRITER=$(aws rds describe-db-clusters --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    "  --query 'DBClusters[0].Endpoint' --output text)",
    'MASTER_SECRET_ARN=$(aws rds describe-db-clusters --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    "  --query 'DBClusters[0].MasterUserSecret.SecretArn' --output text)",
    'SECRET=$(aws secretsmanager get-secret-value --secret-id "$MASTER_SECRET_ARN" \\',
    "  --query SecretString --output text)",
    "",
    'echo "Restored writer endpoint: $WRITER"',
    'echo "Set DATABASE_URL to: postgres://$(echo "$SECRET" | jq -r .username):$(echo "$SECRET" | jq -r .password)@$WRITER:5432/pharmax?sslmode=require"',
    'echo "Then run: pnpm drill:verify"',
    "",
  ].join("\n");
}

export interface TeardownScriptArgs {
  readonly drillClusterId: string;
  readonly drillInstanceId: string;
}

export function composeTeardownScript(args: TeardownScriptArgs): string {
  return [
    "#!/usr/bin/env bash",
    "# Generated by scripts/operations/run-restore-drill.ts --phase=teardown-commands.",
    "# Source of truth for the steps is docs/operations/restore-drill.md §4.",
    "# Drill clusters MUST be destroyed within 24 hours — they are a PHI custody",
    "# risk every minute they live. Aurora teardown is the reverse of provision:",
    "# delete the instance, then disable deletion protection, then delete the cluster.",
    "set -euo pipefail",
    "",
    `NEW_CLUSTER_ID=${shellQuote(args.drillClusterId)}`,
    `NEW_INSTANCE_ID=${shellQuote(args.drillInstanceId)}`,
    "",
    "# ---- Step 1: delete the instance ------------------------------------------",
    "aws rds delete-db-instance \\",
    '  --db-instance-identifier "$NEW_INSTANCE_ID" \\',
    "  --skip-final-snapshot",
    'aws rds wait db-instance-deleted --db-instance-identifier "$NEW_INSTANCE_ID"',
    "",
    "# ---- Step 2: disable deletion protection on the empty cluster -------------",
    "aws rds modify-db-cluster \\",
    '  --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    "  --no-deletion-protection \\",
    "  --apply-immediately",
    "",
    "# ---- Step 3: destroy the cluster ------------------------------------------",
    "aws rds delete-db-cluster \\",
    '  --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    "  --skip-final-snapshot",
    'aws rds wait db-cluster-deleted --db-cluster-identifier "$NEW_CLUSTER_ID"',
    "",
    "# ---- Verify it's gone -----------------------------------------------------",
    'aws rds describe-db-clusters --db-cluster-identifier "$NEW_CLUSTER_ID" \\',
    '  && { echo "FAIL: cluster $NEW_CLUSTER_ID still exists"; exit 1; } \\',
    '  || echo "OK: cluster $NEW_CLUSTER_ID destroyed"',
    "",
  ].join("\n");
}

export interface PreflightResult {
  readonly kmsKeyArn: string;
  readonly kmsHealthy: boolean;
  readonly kmsReason: string | null;
  readonly backupRetentionDays: number;
  readonly latestRestorableTimeIso: string;
}

export interface AuditChainPerOrgRow {
  readonly organizationId: string;
  readonly organizationSlug: string;
  readonly chainValid: boolean;
  readonly verifiedRows: number;
  readonly lastSeq: string | null;
  readonly reason: string | null;
}

export interface VerifyResult {
  readonly smokeConnect: {
    readonly ok: boolean;
    readonly engineVersion: string | null;
    readonly reason: string | null;
  };
  readonly auditChain: {
    readonly ok: boolean;
    readonly orgsChecked: number;
    readonly orgsFailed: number;
    readonly perOrg: ReadonlyArray<AuditChainPerOrgRow>;
  };
  readonly rowCounts: {
    readonly organizations: number;
    readonly users: number;
    readonly orders: number;
    readonly auditLogRows: number;
    readonly eventOutboxRows: number;
  } | null;
  readonly rlsSanity: {
    readonly ok: boolean;
    readonly reason: string | null;
  };
}

export interface DrillRecord {
  readonly quarter: string; // "2026-Q2"
  readonly captain: string;
  readonly observer: string;
  readonly startedAtIso: string;
  readonly completedAtIso: string | null;
  readonly sourceClusterId: string;
  readonly drillClusterId: string;
  readonly drillInstanceId: string;
  readonly restoreTimeIso: string;
  readonly preflight: PreflightResult | null;
  readonly verify: VerifyResult | null;
  readonly teardownConfirmed: boolean;
  readonly findings: ReadonlyArray<string>;
  readonly signOff: string | null;
}

export function composeEvidenceJson(record: DrillRecord): string {
  // Stable key ordering for deterministic diffs across drill periods.
  return `${JSON.stringify(record, null, 2)}\n`;
}

/**
 * Compose the §3 evidence template populated with the actual drill
 * outcome. Output deliberately matches the runbook template line-by-
 * line so an auditor can scan the two side-by-side and confirm "every
 * field the template asks for is present in the captured evidence."
 */
export function composeEvidenceMarkdown(record: DrillRecord): string {
  const lines: string[] = [];
  lines.push(`QUARTERLY AURORA RESTORE DRILL — ${record.quarter}`);
  lines.push("========================================");
  lines.push("");
  lines.push(`Captain:        ${record.captain}`);
  lines.push(`Observer:       ${record.observer}`);
  lines.push(`Started:        ${record.startedAtIso}`);
  lines.push(`Completed:      ${record.completedAtIso ?? "<in flight>"}`);
  lines.push(`Drill cluster:  ${record.drillClusterId}`);
  lines.push(`Drill instance: ${record.drillInstanceId}`);
  lines.push(`Source:         ${record.sourceClusterId}`);
  lines.push(`Restore time:   ${record.restoreTimeIso}`);
  lines.push("");

  lines.push("§1. Provision");
  if (record.preflight !== null) {
    lines.push(
      `- KMS CMK (${record.preflight.kmsKeyArn}): ${formatPassFail(record.preflight.kmsHealthy)}` +
        (record.preflight.kmsReason !== null ? ` — ${record.preflight.kmsReason}` : "")
    );
    lines.push(`- Backup retention: ${record.preflight.backupRetentionDays} day(s)`);
    lines.push(`- Latest restorable time: ${record.preflight.latestRestorableTimeIso}`);
  } else {
    lines.push("- Preflight not captured.");
  }
  lines.push("- aws-cli commands: see <drill-folder>/provision.sh");
  lines.push("");

  lines.push("§2. Verify");
  if (record.verify !== null) {
    const v = record.verify;
    lines.push(
      `- psql smoke connect: ${formatPassFail(v.smokeConnect.ok)}` +
        (v.smokeConnect.engineVersion !== null ? ` — engine ${v.smokeConnect.engineVersion}` : "") +
        (v.smokeConnect.reason !== null ? ` — ${v.smokeConnect.reason}` : "")
    );
    lines.push(
      `- verifyChain across orgs: ${formatPassFail(v.auditChain.ok)} ` +
        `(${v.auditChain.orgsChecked} checked, ${v.auditChain.orgsFailed} failed)`
    );
    if (v.auditChain.orgsFailed > 0) {
      for (const row of v.auditChain.perOrg) {
        if (!row.chainValid) {
          lines.push(`  - BROKEN: ${row.organizationSlug} (${row.organizationId}) — ${row.reason}`);
        }
      }
    }
    if (v.rowCounts !== null) {
      lines.push("- Row counts:");
      lines.push(`  - organizations: ${v.rowCounts.organizations}`);
      lines.push(`  - users:         ${v.rowCounts.users}`);
      lines.push(`  - orders:        ${v.rowCounts.orders}`);
      lines.push(`  - audit_log:     ${v.rowCounts.auditLogRows}`);
      lines.push(`  - event_outbox:  ${v.rowCounts.eventOutboxRows}`);
    } else {
      lines.push("- Row counts: not captured.");
    }
    lines.push(
      `- RLS sanity: ${formatPassFail(v.rlsSanity.ok)}` +
        (v.rlsSanity.reason !== null ? ` — ${v.rlsSanity.reason}` : "")
    );
  } else {
    lines.push("- Verify phase not captured.");
  }
  lines.push("");

  lines.push("§3. Teardown");
  lines.push(`- Destroy confirmed: ${record.teardownConfirmed ? "YES" : "NO"}`);
  if (!record.teardownConfirmed) {
    lines.push(
      "  - NOTE: teardown is intentionally human-driven. " +
        "If the verify phase passed, run `pnpm drill:teardown-commands` for the destroy script."
    );
    lines.push(
      "  - NOTE: if the verify phase FAILED, the cluster is now evidence — " +
        "do NOT destroy. See docs/operations/restore-drill.md § 'Failure mode'."
    );
  }
  lines.push("");

  lines.push("§4. Findings");
  if (record.findings.length === 0) {
    lines.push("- none");
  } else {
    for (const f of record.findings) {
      lines.push(`- ${f}`);
    }
  }
  lines.push("");

  lines.push("§5. Sign-off");
  if (record.signOff !== null) {
    lines.push(record.signOff);
  } else {
    lines.push("- pending");
  }
  lines.push("");

  return lines.join("\n");
}

function formatPassFail(ok: boolean): string {
  return ok ? "PASS" : "FAIL";
}

/**
 * Single-quote a bash literal. The drill scripts only need to handle
 * AWS identifiers + ISO timestamps + AWS resource ARNs, all of which
 * are safe ASCII — but quoting defensively means a future operator
 * passing a value with whitespace doesn't produce a broken script.
 *
 * Escapes single quotes by closing → escaped-quote → reopening: the
 * canonical bash single-quote-escape idiom.
 */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
