// Public surface of @pharmax/database.
//
// Other packages MUST import the Prisma client and types from here, not
// from `@prisma/client` or the generated path directly. This keeps the
// generator location an implementation detail and lets us swap clients
// (e.g. for an Accelerate / Data Proxy variant) without rippling
// imports across the monorepo.

// The canonical, tenancy-enforced client. Application code imports
// THIS. Tenant-scoped models are auto-filtered to the active
// `withTenancyContext` org and fail closed with no frame.
export { prisma } from "./scoped-client.js";
// The raw, UNSCOPED client. Cross-tenant system/bootstrap code only.
export { systemPrisma } from "./client.js";
// Tenant-scoped read wrappers (ORM extension + optional RLS GUC).
export {
  readInTenantContext,
  readInOrgScope,
  readInSystemContext,
  buildReadScopeContext,
  type TenantTransactionClient,
} from "./scoped-read.js";
// Reporting read replica routing (heavy report scans → replica
// connection when REPORTING_DATABASE_URL is set; primary fallback).
export {
  reportingPrisma,
  reportingClientIsReplica,
  readReportingInOrgScope,
} from "./reporting-client.js";
export * as billing from "./billing/index.js";
export * as phi from "./phi/index.js";
export {
  Prisma,
  PrismaClient,
  // Enums (re-exported for ergonomic value-side usage in commands/seeds)
  ApiKeyQuotaTier,
  ApiKeyStatus,
  AuthSessionRevokeReason,
  BucketKind,
  CancellationDisposition,
  CarrierCredentialStatus,
  ClerkWebhookEventStatus,
  ClinicStatus,
  CommandStatus,
  EasyPostWebhookEventStatus,
  FedExWebhookEventStatus,
  HoldReason,
  HoldReleaseReason,
  OrderStageIntervalKind,
  IntakeSourceKind,
  InventoryTransactionReason,
  InvoiceLineKind,
  InvoiceStatus,
  LabelPrinterConnection,
  LabelPrinterProtocol,
  LabelPrinterStatus,
  LabelPrinterVendor,
  LabelStockKind,
  LoginOutcome,
  LotStatus,
  MfaType,
  NotificationDeliveryStatus,
  ResendWebhookEventStatus,
  OrderLineStatus,
  OrderPriority,
  OrderStatus,
  OrganizationStatus,
  OutboxStatus,
  PackagePhotoMatchStrategy,
  PackagePhotoTrackingSource,
  PatientStatus,
  AllergyCategory,
  AllergyClinicalStatus,
  AllergyCriticality,
  AllergyHistoryAssertionStatus,
  AllergyIntoleranceType,
  AllergyReactionManifestation,
  AllergyReactionSeverity,
  AllergySubstanceCodeSystem,
  AllergyVerificationStatus,
  PaymentKind,
  CompoundBudBasis,
  CompoundFormulaRetireReason,
  CompoundFormulaStatus,
  CompoundingQualityOutcome,
  CompoundIngredientCoding,
  CompoundPreparationKind,
  CompoundStorageCondition,
  ControlledSubstancePartialFillBasis,
  ControlledSubstanceSchedule,
  ClinicCreditEntryKind,
  ClinicCreditSource,
  PaymentMethod,
  PortalAccountStatus,
  PrescriptionStatus,
  PricingRuleStatus,
  PrintJobStatus,
  ProviderOnboardingProofingOutcome,
  ProviderOnboardingStatus,
  ProviderStatus,
  ReopenReason,
  ReportScheduleNotifyOn,
  ReportScheduleRunStatus,
  ReportScheduleStatus,
  ProductNdcKind,
  RoleScope,
  RxnormReleaseStatus,
  ScreeningPhase,
  ShipmentCarrier,
  ShipmentStatus,
  ShipmentTrackingEventKind,
  ShipmentTrackingSource,
  ShippingProvider,
  SiteStatus,
  StripeWebhookEventStatus,
  TeamStatus,
  UserStatus,
  VerificationDecision,
  VerificationStage,
  WebAuthnCeremony,
  WebhookDeliveryStatus,
  WebhookSubscriptionStatus,
  WorkflowPolicyOverlayStatus,
  WorkflowPolicyStatus,
  WorkstationStatus,
} from "./generated/client/client.js";

// Row types (re-exported so consumers depend on @pharmax/database, not
// on @prisma/client or the generated client path directly). Add new
// models here as the schema grows; missing exports surface as TS2305
// errors at the consumption site.
export type {
  ApiKey,
  AuditChainState,
  AuditLog,
  AuthSession,
  Bucket,
  Clinic,
  ClinicSite,
  CommandLog,
  CompoundFormula,
  CompoundFormulaIngredient,
  CompoundingRecord,
  CompoundingRecordIngredient,
  ControlledSubstanceDispensing,
  DscsaTransaction,
  EventOutbox,
  IdempotencyKey,
  InventoryTransaction,
  Invoice,
  InvoiceLine,
  LabelPrinter,
  LoginAttempt,
  Lot,
  LotAssignment,
  MfaEnrollment,
  Order,
  OrderCancellation,
  OrderCorrectionReopen,
  OrderEvent,
  OrderHold,
  OrderLine,
  OrderScreeningAcknowledgement,
  OrderScreeningFinding,
  OrderStageInterval,
  Organization,
  PasswordHistory,
  PasswordResetToken,
  Patient,
  PharmacySite,
  Permission,
  PortalAccount,
  PortalPasswordHistory,
  PortalSession,
  PortalSetupToken,
  Prescription,
  RecoveryCode,
  PrintJob,
  PrintTemplate,
  Product,
  Provider,
  ProviderOnboardingApplication,
  ReportRun,
  ReportSchedule,
  NotificationDelivery,
  ResendWebhookEvent,
  Role,
  RolePermission,
  RxnormNdcProduct,
  RxnormProductIngredient,
  RxnormRelease,
  CarrierCredential,
  ClerkWebhookEvent,
  EasyPostWebhookEvent,
  FedExWebhookEvent,
  Shipment,
  ShipmentTrackingEvent,
  StripeCustomer,
  StripeWebhookEvent,
  Team,
  User,
  UserRole,
  VialLabel,
  VerificationRecord,
  WebAuthnChallenge,
  WebAuthnCredential,
  WebhookDelivery,
  WebhookSubscription,
  WorkflowPolicy,
  Workstation,
} from "./generated/client/client.js";
